services:
  postgres:
    image: postgres:latest
    container_name: crowdsourcing_postgres_db
    env_file:
      - .env.docker
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - crowdsourcing_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crowdsourcing_backend
    env_file:
      - .env.docker
    ports:
      - "${PORT}:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - crowdsourcing_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  crowdsourcing_network:
    driver: bridge